spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: true

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}

  docker:
    compose:
      enabled: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_EXPIRATION:2592000000}

logging:
  level:
    root: WARN
    net.nexhash.chargeflow: INFO

server:
  port: ${PORT:8080}